// <auto-generated>
//
// This file was automatically generated by Interoptopus.
//
// Library:      tao
// Hash:         0xcafaa7c7d0497b8
// Namespace:    Enx.Tao.Internal
// Builder:      interoptopus_csharp (0.16.0-alpha.16)
//
// Do not edit this file manually.
//
// </auto-generated>

// We use [Obsolete()] to discourage users calling internal code. Disable internal warnings about that.
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete (with message)
// Simplifies codegen
#pragma warning disable CS0105 // The using directive appeared previously in this namespace
#nullable enable
// Generated interop code uses patterns that trigger nullable diagnostics
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602 // Dereference of a possibly null reference
#pragma warning disable CS8603 // Possible null reference return
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor

#pragma warning disable 0105
using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Runtime.CompilerServices;

#pragma warning restore 0105


namespace Enx.Tao.Internal;

public static partial class Interop {

    public const string NativeLib = "tao";
}

[Serializable]
[StructLayout(LayoutKind.Sequential)]
public partial struct Bool
{
    byte value;
}

public partial struct Bool
{
    public static readonly Bool True = new Bool { value = 1 };
    public static readonly Bool False = new Bool { value = 0 };

    public Bool(bool b)
    {
        value = (byte)(b ? 1 : 0);
    }

    public bool Is => value == 1;

    public static implicit operator Bool(bool b) => new Bool(b);
    public static implicit operator bool(Bool b) => b.Is;
}

public class InteropException(string text) : Exception(text) { }

public class EnumException() : InteropException($"Enum variant mismatch.")  { }

public class EnumException<T>(T t) : InteropException($"Enum variant mismatch.")
{
    public T Value { get; } = t;
}

[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal delegate void AsyncCallbackCommon(IntPtr data, IntPtr callback_data);

[StructLayout(LayoutKind.Sequential)]
internal partial struct AsyncCallbackCommonNative
{
    internal IntPtr _ptr;
    internal IntPtr _ts;
}

internal partial struct AsyncCallbackCommonNative
{
    /// Signals completion with no return value (corresponds to <c>AsyncCallback&lt;()&gt;</c> on the Rust side).
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal unsafe void UnsafeComplete()
    {
        if (_ptr == IntPtr.Zero) return;
        var fn = (delegate* unmanaged[Cdecl]<void*, IntPtr, void>)_ptr;
        // &() in Rust is a valid zero-sized reference; pass a non-null dummy so Rust never sees null.
        byte dummy = 0;
        fn(&dummy, _ts);
    }

    /// Signals completion with a value (corresponds to <c>AsyncCallback&lt;T&gt;</c> on the Rust side).
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal unsafe void UnsafeComplete<T>(T t) where T : unmanaged
    {
        if (_ptr == IntPtr.Zero) return;
        var fn = (delegate* unmanaged[Cdecl]<T*, IntPtr, void>)_ptr;
        fn(&t, _ts);
    }
}

[CustomMarshaller(typeof(string), MarshalMode.ManagedToUnmanagedOut, typeof(ConstCStrMarshaller))]
internal static class ConstCStrMarshaller
{
    public static unsafe string? ConvertToManaged(byte* unmanaged)
        => unmanaged == null ? null : Marshal.PtrToStringAnsi((nint)unmanaged);
}

[StructLayout(LayoutKind.Sequential)]
internal partial struct TaskHandle
{
    private IntPtr _data;
    private IntPtr _abort_fn;
    private IntPtr _drop_fn;
}

internal partial struct TaskHandle : IDisposable
{
    /// Aborts the associated Rust async task. The spawned future will be
    /// dropped at its next <c>.await</c> point and the completion callback
    /// will fire with a <c>Panic</c> result.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal unsafe void Abort()
    {
        if (_abort_fn != IntPtr.Zero && _data != IntPtr.Zero)
        {
            ((delegate* unmanaged[Cdecl]<IntPtr, void>)_abort_fn)(_data);
        }
    }

    /// Frees the native handle resources without aborting the task.
    /// Must be called exactly once when the handle is no longer needed.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public unsafe void Dispose()
    {
        if (_drop_fn != IntPtr.Zero && _data != IntPtr.Zero)
        {
            ((delegate* unmanaged[Cdecl]<IntPtr, void>)_drop_fn)(_data);
            _data = IntPtr.Zero;
            _abort_fn = IntPtr.Zero;
            _drop_fn = IntPtr.Zero;
        }
    }

    /// Creates a <see cref="TaskHandle"/> backed by a <see cref="CancellationTokenSource"/>.
    /// Calling <c>Abort</c> on the returned handle triggers <see cref="CancellationTokenSource.Cancel"/>;
    /// calling <c>Dispose</c> frees the pinned GCHandle.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal static unsafe TaskHandle FromCancellationTokenSource(CancellationTokenSource cts)
    {
        var gcHandle = GCHandle.Alloc(cts);
        return new TaskHandle
        {
            _data = GCHandle.ToIntPtr(gcHandle),
            _abort_fn = (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, void>)&TaskHandleAbort,
            _drop_fn = (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, void>)&TaskHandleDrop,
        };
    }

    [UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    private static void TaskHandleAbort(IntPtr data)
    {
        var handle = GCHandle.FromIntPtr(data);
        if (handle.Target is CancellationTokenSource cts)
        {
            cts.Cancel();
        }
    }

    [UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    private static void TaskHandleDrop(IntPtr data)
    {
        var handle = GCHandle.FromIntPtr(data);
        if (handle.Target is CancellationTokenSource cts)
        {
            cts.Cancel();
            cts.Dispose();
        }
        handle.Free();
    }
}
