// <auto-generated>
//
// This file was automatically generated by Interoptopus.
//
// Library:      tao
// Hash:         0xcafaa7c7d0497b8
// Namespace:    Enx.Tao.Internal
// Builder:      interoptopus_csharp (0.16.0-alpha.16)
//
// Do not edit this file manually.
//
// </auto-generated>

// We use [Obsolete()] to discourage users calling internal code. Disable internal warnings about that.
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete (with message)
// Simplifies codegen
#pragma warning disable CS0105 // The using directive appeared previously in this namespace
#nullable enable
// Generated interop code uses patterns that trigger nullable diagnostics
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602 // Dereference of a possibly null reference
#pragma warning disable CS8603 // Possible null reference return
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor

#pragma warning disable 0105
using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Runtime.CompilerServices;

#pragma warning restore 0105


namespace Enx.Tao.Internal;

public static partial class Interop {

    public const string NativeLib = "tao";

    static Interop()
    {
        var api_version = Interop.__api_guard();
        if (api_version != 0xcafaa7c7d0497b8)
        {
            throw new TypeLoadException($"API reports hash 0x{api_version:X} which differs from hash in bindings (0xcafaa7c7d0497b8). You probably forgot to update / copy either the bindings or the library.");
        }
    }

    
    [LibraryImport(NativeLib, EntryPoint = "__api_guard")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static partial ulong __api_guard();
}


